version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "daily"

  # Maintain dependencies for docker for dev environment
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
