name: Run Python/Django test suite

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run Django collectstatic management command
      run: python manage.py collectstatic
    - name: Run Python 3.9/Django tests
      run: python manage.py test